#!/usr/bin/bash
# if
# && || !

# -e -> regardless of type
# -f -> file
# -d -> directory

if [[ -f $0 ]]; then
	echo "file exists..." 
fi
if [[ -d $0 ]]; then
	echo "dir exists..." 
fi
if [[ -e $0 ]]; then
	echo "exists..." 
fi

echo $0


# == != > >= < <=
read -p "Number? " n
# if (( n > 10 )) -> wrong case
if ((n > 10)); then
	echo "bigger than 10"
fi

